### ISSUE TITLE
format incompatible with colors

### ISSUE THREAD

**Issue by syntonym** [gravmatt/py-term#2]
Formatting first and then using `center` or `right` produces wrong output: 

```
writeLine(right(format("hello!", red)))
                                                                                                                                                                           hello! (here is some space)
```

That is because in `return ' '*(getSize()[1]/2 - len(text)/2) + text` the len will also count the "invisible" color codes.

You could strip "invisible" chars and then use len to get the "visible length".

**Comment by gravmatt** [comment]
Bam.. fixed! 🍩
