### ISSUE TITLE
Please find terminal size programatically

### ISSUE THREAD

**Issue by kseistrup** [gravmatt/py-term#4]
Please only call an external program as a last resort. Try something like [this](https://stackoverflow.com/a/566752) — it uses calls to `ioctl()` and environment variables. If all of these fails, you could call an external program.

**Comment by gravmatt** [comment]
@kseistrup you are right. It was a quick solution as I made it. But I thing I found a better way that uses environment variables in first place

**Comment by kseistrup** [comment]
It turns out Python 3.3+ has a [method](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size) of finding the terminal size:

``` py
>>> import shutil
>>> termsize = shutil.get_terminal_size()
>>> (termsize.lines, termsize.columns)
(60, 191)
>>>
```

See also [the relevant section of the `os` module](https://docs.python.org/3/library/os.html#querying-the-size-of-a-terminal).

**Comment by gravmatt** [comment]
Found this method already but I'm looking also for a python 2.6+ solution. Check out my latest commit on that [d586fbf](https://github.com/gravmatt/py-term/commit/d586fbf0abc9d5b8e20481d7e00774e66ef3ecf4).

**Comment by kseistrup** [comment]
Looks good, except you should probably wrap it in a `try`/`except` that catches `OSError` (happens if `.isatty()` is false).

**Comment by gravmatt** [comment]
@kseistrup do you have some windows experience? I would like to make it Windows compatible. So I found this code snippet but I don't know if it works on all windows platforms _(win 7 and 8 would be great)_.

Before I start searching for testing options I ask you first 😅

```
def _get_terminal_size_windows():
    try:
        from ctypes import windll, create_string_buffer
        # stdin handle is -10
        # stdout handle is -11
        # stderr handle is -12
        h = windll.kernel32.GetStdHandle(-12)
        csbi = create_string_buffer(22)
        res = windll.kernel32.GetConsoleScreenBufferInfo(h, csbi)
        if res:
            (bufx, bufy, curx, cury, wattr,
             left, top, right, bottom,
             maxx, maxy) = struct.unpack("hhhhHhhhhhh", csbi.raw)
            sizex = right - left + 1
            sizey = bottom - top + 1
            return sizex, sizey
    except:
        pass
```

**Comment by kseistrup** [comment]
I'm afraid I have to pass here, I've never done programming on Windows and I don't even have access to a Windows machine.

**Comment by gravmatt** [comment]
@kseistrup Me too. But its python.. its platform independent. so I thing I have to make it work on windows as well. But thanks so far!!
